%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'peru';
M_.dynare_version = '4.5.5';
oo_.dynare_version = '4.5.5';
options_.dynare_version = '4.5.5';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('peru.log');
M_.exo_names = 'eps_a';
M_.exo_names_tex = 'eps\_a';
M_.exo_names_long = 'eps_a';
M_.exo_names = char(M_.exo_names, 'eps_v');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_v');
M_.exo_names_long = char(M_.exo_names_long, 'eps_v');
M_.exo_names = char(M_.exo_names, 'eps_phistar');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_phistar');
M_.exo_names_long = char(M_.exo_names_long, 'eps_phistar');
M_.exo_names = char(M_.exo_names, 'eps_ystar');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_ystar');
M_.exo_names_long = char(M_.exo_names_long, 'eps_ystar');
M_.exo_names = char(M_.exo_names, 'eps_rstar');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_rstar');
M_.exo_names_long = char(M_.exo_names_long, 'eps_rstar');
M_.endo_names = 'pd';
M_.endo_names_tex = 'pd';
M_.endo_names_long = 'pd';
M_.endo_names = char(M_.endo_names, 'pc');
M_.endo_names_tex = char(M_.endo_names_tex, 'pc');
M_.endo_names_long = char(M_.endo_names_long, 'pc');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'd');
M_.endo_names_tex = char(M_.endo_names_tex, 'd');
M_.endo_names_long = char(M_.endo_names_long, 'd');
M_.endo_names = char(M_.endo_names, 'rl');
M_.endo_names_tex = char(M_.endo_names_tex, 'rl');
M_.endo_names_long = char(M_.endo_names_long, 'rl');
M_.endo_names = char(M_.endo_names, 'l');
M_.endo_names_tex = char(M_.endo_names_tex, 'l');
M_.endo_names_long = char(M_.endo_names_long, 'l');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'inv');
M_.endo_names_tex = char(M_.endo_names_tex, 'inv');
M_.endo_names_long = char(M_.endo_names_long, 'inv');
M_.endo_names = char(M_.endo_names, 'phi_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi\_h');
M_.endo_names_long = char(M_.endo_names_long, 'phi_h');
M_.endo_names = char(M_.endo_names, 'vn');
M_.endo_names_tex = char(M_.endo_names_tex, 'vn');
M_.endo_names_long = char(M_.endo_names_long, 'vn');
M_.endo_names = char(M_.endo_names, 'vd');
M_.endo_names_tex = char(M_.endo_names_tex, 'vd');
M_.endo_names_long = char(M_.endo_names_long, 'vd');
M_.endo_names = char(M_.endo_names, 'cm_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'cm\_h');
M_.endo_names_long = char(M_.endo_names_long, 'cm_h');
M_.endo_names = char(M_.endo_names, 'p_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'p\_h');
M_.endo_names_long = char(M_.endo_names_long, 'p_h');
M_.endo_names = char(M_.endo_names, 'ti');
M_.endo_names_tex = char(M_.endo_names_tex, 'ti');
M_.endo_names_long = char(M_.endo_names_long, 'ti');
M_.endo_names = char(M_.endo_names, 'e');
M_.endo_names_tex = char(M_.endo_names_tex, 'e');
M_.endo_names_long = char(M_.endo_names_long, 'e');
M_.endo_names = char(M_.endo_names, 'b');
M_.endo_names_tex = char(M_.endo_names_tex, 'b');
M_.endo_names_long = char(M_.endo_names_long, 'b');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'tau');
M_.endo_names_tex = char(M_.endo_names_tex, 'tau');
M_.endo_names_long = char(M_.endo_names_long, 'tau');
M_.endo_names = char(M_.endo_names, 'yd');
M_.endo_names_tex = char(M_.endo_names_tex, 'yd');
M_.endo_names_long = char(M_.endo_names_long, 'yd');
M_.endo_names = char(M_.endo_names, 'phic');
M_.endo_names_tex = char(M_.endo_names_tex, 'phic');
M_.endo_names_long = char(M_.endo_names_long, 'phic');
M_.endo_names = char(M_.endo_names, 'phistar_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'phistar\_f');
M_.endo_names_long = char(M_.endo_names_long, 'phistar_f');
M_.endo_names = char(M_.endo_names, 'ystar');
M_.endo_names_tex = char(M_.endo_names_tex, 'ystar');
M_.endo_names_long = char(M_.endo_names_long, 'ystar');
M_.endo_names = char(M_.endo_names, 'rstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'rstar');
M_.endo_names_long = char(M_.endo_names_long, 'rstar');
M_.endo_names = char(M_.endo_names, 'v');
M_.endo_names_tex = char(M_.endo_names_tex, 'v');
M_.endo_names_long = char(M_.endo_names_long, 'v');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_17_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_17\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_17_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_1_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_1\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_1_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_7_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_7\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_7_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_8_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_8\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_8_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_24_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_24\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_24_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_25_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_25\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_25_1');
M_.endo_partitions = struct();
M_.param_names = 'beta';
M_.param_names_tex = 'beta';
M_.param_names_long = 'beta';
M_.param_names = char(M_.param_names, 'psi');
M_.param_names_tex = char(M_.param_names_tex, 'psi');
M_.param_names_long = char(M_.param_names_long, 'psi');
M_.param_names = char(M_.param_names, 'c_ss');
M_.param_names_tex = char(M_.param_names_tex, 'c\_ss');
M_.param_names_long = char(M_.param_names_long, 'c_ss');
M_.param_names = char(M_.param_names, 'eps');
M_.param_names_tex = char(M_.param_names_tex, 'eps');
M_.param_names_long = char(M_.param_names_long, 'eps');
M_.param_names = char(M_.param_names, 'yd_ss');
M_.param_names_tex = char(M_.param_names_tex, 'yd\_ss');
M_.param_names_long = char(M_.param_names_long, 'yd_ss');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'pd_ss');
M_.param_names_tex = char(M_.param_names_tex, 'pd\_ss');
M_.param_names_long = char(M_.param_names_long, 'pd_ss');
M_.param_names = char(M_.param_names, 'pc_ss');
M_.param_names_tex = char(M_.param_names_tex, 'pc\_ss');
M_.param_names_long = char(M_.param_names_long, 'pc_ss');
M_.param_names = char(M_.param_names, 'varphi');
M_.param_names_tex = char(M_.param_names_tex, 'varphi');
M_.param_names_long = char(M_.param_names_long, 'varphi');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names_long = char(M_.param_names_long, 'alpha');
M_.param_names = char(M_.param_names, 'omega');
M_.param_names_tex = char(M_.param_names_tex, 'omega');
M_.param_names_long = char(M_.param_names_long, 'omega');
M_.param_names = char(M_.param_names, 'sigma_c');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_c');
M_.param_names_long = char(M_.param_names_long, 'sigma_c');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names_long = char(M_.param_names_long, 'eta');
M_.param_names = char(M_.param_names, 'gamma');
M_.param_names_tex = char(M_.param_names_tex, 'gamma');
M_.param_names_long = char(M_.param_names_long, 'gamma');
M_.param_names = char(M_.param_names, 'p_h_ss');
M_.param_names_tex = char(M_.param_names_tex, 'p\_h\_ss');
M_.param_names_long = char(M_.param_names_long, 'p_h_ss');
M_.param_names = char(M_.param_names, 'theta_h');
M_.param_names_tex = char(M_.param_names_tex, 'theta\_h');
M_.param_names_long = char(M_.param_names_long, 'theta_h');
M_.param_names = char(M_.param_names, 'ti_ss');
M_.param_names_tex = char(M_.param_names_tex, 'ti\_ss');
M_.param_names_long = char(M_.param_names_long, 'ti_ss');
M_.param_names = char(M_.param_names, 'inv_ss');
M_.param_names_tex = char(M_.param_names_tex, 'inv\_ss');
M_.param_names_long = char(M_.param_names_long, 'inv_ss');
M_.param_names = char(M_.param_names, 'q_ss');
M_.param_names_tex = char(M_.param_names_tex, 'q\_ss');
M_.param_names_long = char(M_.param_names_long, 'q_ss');
M_.param_names = char(M_.param_names, 'ystar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'ystar\_ss');
M_.param_names_long = char(M_.param_names_long, 'ystar_ss');
M_.param_names = char(M_.param_names, 'rl_ss');
M_.param_names_tex = char(M_.param_names_tex, 'rl\_ss');
M_.param_names_long = char(M_.param_names_long, 'rl_ss');
M_.param_names = char(M_.param_names, 'r_ss');
M_.param_names_tex = char(M_.param_names_tex, 'r\_ss');
M_.param_names_long = char(M_.param_names_long, 'r_ss');
M_.param_names = char(M_.param_names, 'kappa');
M_.param_names_tex = char(M_.param_names_tex, 'kappa');
M_.param_names_long = char(M_.param_names_long, 'kappa');
M_.param_names = char(M_.param_names, 'ttau');
M_.param_names_tex = char(M_.param_names_tex, 'ttau');
M_.param_names_long = char(M_.param_names_long, 'ttau');
M_.param_names = char(M_.param_names, 'gamma_r');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_r');
M_.param_names_long = char(M_.param_names_long, 'gamma_r');
M_.param_names = char(M_.param_names, 'gamma_phi');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_phi');
M_.param_names_long = char(M_.param_names_long, 'gamma_phi');
M_.param_names = char(M_.param_names, 'gamma_y');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_y');
M_.param_names_long = char(M_.param_names_long, 'gamma_y');
M_.param_names = char(M_.param_names, 'gamma_b');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_b');
M_.param_names_long = char(M_.param_names_long, 'gamma_b');
M_.param_names = char(M_.param_names, 'rho1a');
M_.param_names_tex = char(M_.param_names_tex, 'rho1a');
M_.param_names_long = char(M_.param_names_long, 'rho1a');
M_.param_names = char(M_.param_names, 'rho2a');
M_.param_names_tex = char(M_.param_names_tex, 'rho2a');
M_.param_names_long = char(M_.param_names_long, 'rho2a');
M_.param_names = char(M_.param_names, 'rho1v');
M_.param_names_tex = char(M_.param_names_tex, 'rho1v');
M_.param_names_long = char(M_.param_names_long, 'rho1v');
M_.param_names = char(M_.param_names, 'rho1p');
M_.param_names_tex = char(M_.param_names_tex, 'rho1p');
M_.param_names_long = char(M_.param_names_long, 'rho1p');
M_.param_names = char(M_.param_names, 'rho1y');
M_.param_names_tex = char(M_.param_names_tex, 'rho1y');
M_.param_names_long = char(M_.param_names_long, 'rho1y');
M_.param_names = char(M_.param_names, 'rho1r');
M_.param_names_tex = char(M_.param_names_tex, 'rho1r');
M_.param_names_long = char(M_.param_names_long, 'rho1r');
M_.param_names = char(M_.param_names, 'rho2y');
M_.param_names_tex = char(M_.param_names_tex, 'rho2y');
M_.param_names_long = char(M_.param_names_long, 'rho2y');
M_.param_names = char(M_.param_names, 'rho2r');
M_.param_names_tex = char(M_.param_names_tex, 'rho2r');
M_.param_names_long = char(M_.param_names_long, 'rho2r');
M_.param_names = char(M_.param_names, 'a_ss');
M_.param_names_tex = char(M_.param_names_tex, 'a\_ss');
M_.param_names_long = char(M_.param_names_long, 'a_ss');
M_.param_names = char(M_.param_names, 'y_ss');
M_.param_names_tex = char(M_.param_names_tex, 'y\_ss');
M_.param_names_long = char(M_.param_names_long, 'y_ss');
M_.param_names = char(M_.param_names, 'd_ss');
M_.param_names_tex = char(M_.param_names_tex, 'd\_ss');
M_.param_names_long = char(M_.param_names_long, 'd_ss');
M_.param_names = char(M_.param_names, 'invd_ss');
M_.param_names_tex = char(M_.param_names_tex, 'invd\_ss');
M_.param_names_long = char(M_.param_names_long, 'invd_ss');
M_.param_names = char(M_.param_names, 'b_ss');
M_.param_names_tex = char(M_.param_names_tex, 'b\_ss');
M_.param_names_long = char(M_.param_names_long, 'b_ss');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 5;
M_.endo_nbr = 33;
M_.param_nbr = 41;
M_.orig_endo_nbr = 27;
M_.aux_vars(1).endo_index = 28;
M_.aux_vars(1).type = 1;
M_.aux_vars(1).orig_index = 18;
M_.aux_vars(1).orig_lead_lag = -1;
M_.aux_vars(2).endo_index = 29;
M_.aux_vars(2).type = 1;
M_.aux_vars(2).orig_index = 2;
M_.aux_vars(2).orig_lead_lag = -1;
M_.aux_vars(3).endo_index = 30;
M_.aux_vars(3).type = 1;
M_.aux_vars(3).orig_index = 8;
M_.aux_vars(3).orig_lead_lag = -1;
M_.aux_vars(4).endo_index = 31;
M_.aux_vars(4).type = 1;
M_.aux_vars(4).orig_index = 9;
M_.aux_vars(4).orig_lead_lag = -1;
M_.aux_vars(5).endo_index = 32;
M_.aux_vars(5).type = 1;
M_.aux_vars(5).orig_index = 25;
M_.aux_vars(5).orig_lead_lag = -1;
M_.aux_vars(6).endo_index = 33;
M_.aux_vars(6).type = 1;
M_.aux_vars(6).orig_index = 26;
M_.aux_vars(6).orig_lead_lag = -1;
M_.Sigma_e = zeros(5, 5);
M_.Correlation_matrix = eye(5, 5);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('peru_static');
erase_compiled_function('peru_dynamic');
M_.orig_eq_nbr = 27;
M_.eq_nbr = 33;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 22 55;
 1 23 56;
 2 24 57;
 3 25 0;
 4 26 0;
 0 27 0;
 0 28 0;
 5 29 0;
 6 30 0;
 0 31 0;
 0 32 58;
 0 33 59;
 0 34 60;
 0 35 0;
 7 36 0;
 8 37 0;
 9 38 61;
 10 39 0;
 11 40 0;
 0 41 0;
 0 42 0;
 0 43 0;
 0 44 0;
 12 45 0;
 13 46 0;
 14 47 0;
 15 48 0;
 16 49 0;
 17 50 0;
 18 51 0;
 19 52 0;
 20 53 0;
 21 54 0;]';
M_.nstatic = 8;
M_.nfwrd   = 4;
M_.npred   = 18;
M_.nboth   = 3;
M_.nsfwrd   = 7;
M_.nspred   = 21;
M_.ndynamic   = 25;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:5];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(33, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(5, 1);
M_.params = NaN(41, 1);
M_.NNZDerivatives = [139; 0; -1];
M_.params( 1 ) = 0.9975;
beta = M_.params( 1 );
M_.params( 2 ) = 0.5;
psi = M_.params( 2 );
M_.params( 4 ) = 0.75;
eps = M_.params( 4 );
M_.params( 6 ) = 0.025;
delta = M_.params( 6 );
M_.params( 7 ) = 1;
pd_ss = M_.params( 7 );
M_.params( 8 ) = M_.params(7);
pc_ss = M_.params( 8 );
M_.params( 9 ) = 2;
varphi = M_.params( 9 );
M_.params( 10 ) = 0.1;
alpha = M_.params( 10 );
M_.params( 11 ) = 0.75;
omega = M_.params( 11 );
M_.params( 12 ) = 6;
sigma_c = M_.params( 12 );
M_.params( 13 ) = (-1);
eta = M_.params( 13 );
M_.params( 14 ) = 0.15;
gamma = M_.params( 14 );
M_.params( 15 ) = 1;
p_h_ss = M_.params( 15 );
M_.params( 16 ) = 0.8;
theta_h = M_.params( 16 );
M_.params( 17 ) = 1;
ti_ss = M_.params( 17 );
M_.params( 19 ) = 1;
q_ss = M_.params( 19 );
M_.params( 21 ) = 1/M_.params(1);
rl_ss = M_.params( 21 );
M_.params( 22 ) = 1/M_.params(1);
r_ss = M_.params( 22 );
M_.params( 23 ) = 0.1;
kappa = M_.params( 23 );
M_.params( 24 ) = 0.4;
ttau = M_.params( 24 );
M_.params( 25 ) = 0.7;
gamma_r = M_.params( 25 );
M_.params( 26 ) = 1.5;
gamma_phi = M_.params( 26 );
M_.params( 27 ) = 0.1;
gamma_y = M_.params( 27 );
M_.params( 28 ) = 0.5;
gamma_b = M_.params( 28 );
M_.params( 29 ) = 0.9;
rho1a = M_.params( 29 );
M_.params( 30 ) = 0.9;
rho2a = M_.params( 30 );
M_.params( 31 ) = 0.9;
rho1v = M_.params( 31 );
M_.params( 32 ) = 0.9;
rho1p = M_.params( 32 );
M_.params( 33 ) = 0.9;
rho1y = M_.params( 33 );
M_.params( 34 ) = 0.9;
rho1r = M_.params( 34 );
M_.params( 35 ) = 0.9;
rho2y = M_.params( 35 );
M_.params( 36 ) = 0.9;
rho2r = M_.params( 36 );
M_.params( 37 ) = 1-0.6*(1-M_.params(1))/M_.params(1);
a_ss = M_.params( 37 );
M_.params( 38 ) = (M_.params(2)/(1-M_.params(4))*(M_.params(12)-1)/M_.params(12)*(1+(1-M_.params(4))*(1-M_.params(2))/M_.params(2)*M_.params(6)/(1-M_.params(1)*(1-M_.params(6))))/M_.params(37))^(1/(1+M_.params(9)));
y_ss = M_.params( 38 );
M_.params( 18 ) = 0.2*M_.params(38);
inv_ss = M_.params( 18 );
M_.params( 20 ) = M_.params(38)*(1-M_.params(37)*(1-M_.params(14)))/M_.params(14);
ystar_ss = M_.params( 20 );
M_.params( 3 ) = M_.params(38)*oo_.steady_state(9)*(1+(1-M_.params(4))*(1-M_.params(2))/M_.params(2)*M_.params(6)/(1-M_.params(1)*(1-M_.params(6))))^(-1);
c_ss = M_.params( 3 );
M_.params( 39 ) = (M_.params(37)*M_.params(38)-M_.params(3))/M_.params(6);
d_ss = M_.params( 39 );
M_.params( 40 ) = M_.params(6)*M_.params(39);
invd_ss = M_.params( 40 );
M_.params( 5 ) = M_.params(40);
yd_ss = M_.params( 5 );
M_.params( 41 ) = 0.6;
b_ss = M_.params( 41 );
oo_.dr.eigval = check(M_,options_,oo_);
steady;
save('peru_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('peru_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('peru_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('peru_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('peru_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('peru_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('peru_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
